# Generated by Django 3.2 on 2021-05-29 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(default=datetime.datetime(2021, 5, 29, 15, 18, 55, 283969, tzinfo=utc)),
        ),
    ]
